title: Default
pages:
  template:
    - module.text
    - module.text-2
    - module.quote
    - module.hero
    - module.gallery
    - module.preview-left
    - module.preview-right
files: true

fields:
  title:
    label: Title
    type:  text

  sortable:
    label: Sortable
    type:  sortable

    layout:  base
    variant: null

    limit: false

    parent: null
    prefix: null

    options:
      limit: false