title: Default
pages:
  template:
    - module.hero
    - module.intro
    - module.section
    - module.preview
    - module.list
files: true

fields:
  title:
    label: Title
    type:  text

  sortable:
    label: Sortable
    type:  sortable

    layout:  base
    variant: null

    limit: false

    parent: null
    prefix: null

    options:
      limit: false