title: Site
pages: default
fields:
  title:
    label: Title
    type:  text
  author:
    label: Author
    type:  text
  description:
    label: Description
    type:  textarea
  keywords:
    label: Keywords
    type:  tags
  dribbble:
    label: Dribbble
    type: url
    width: 1/3
  instagram:
    label: Instagram
    type: url
    width: 1/3
  twitter:
    label: Twitter
    type: url
    width: 1/3
  copyright:
    label: Copyright
    type:  textarea
